### ISSUE TITLE
Implement Footer Design

### ISSUE THREAD

**Issue by Artzalife** [PB-J/frontline-frontend#36]
From reference files create footer for mobile and desktop.
![Footer- Mobile](https://user-images.githubusercontent.com/80708838/111193779-ec3ae680-8590-11eb-8652-7d77cf43b430.png)
![Footer Specs](https://user-images.githubusercontent.com/80708838/111193781-ec3ae680-8590-11eb-9059-7b794ab902e1.png)

**Comment by simonchen92** [comment]
closing this issue with PR #43 fixing this
