### ISSUE TITLE
Update wording to "Location" in post modal

### ISSUE THREAD

**Issue by Artzalife** [PB-J/frontline-frontend#41]
Please change the wording from "state" to "location" in the create a post modal. Users are tagging both cities and states, so this term makes much more sense. 

<img width="346" alt="change to location" src="https://user-images.githubusercontent.com/80708838/111211060-5ad56f80-85a4-11eb-8ac2-65989e34811d.png">

**Comment by simonchen92** [comment]
Fixed requested issue with PR #45
